-- Explicit couple identity and central Wishlist write guard.
--
-- Existing production has two app users. They are backfilled into one couple.
-- Future users must be added to couple_members explicitly and never inherit
-- access merely because they have an authenticated account.

begin;

alter table public.users
  add column if not exists auth_user_id uuid references auth.users(id) on delete set null;

update public.users u
set auth_user_id = au.id
from auth.users au
where u.auth_user_id is null
  and u.email is not null
  and lower(au.email) = lower(u.email);

create unique index if not exists users_auth_user_id_uidx
  on public.users (auth_user_id)
  where auth_user_id is not null;

create table if not exists public.couples (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now()
);

create table if not exists public.couple_members (
  couple_id bigint not null references public.couples(id) on delete cascade,
  user_id integer not null references public.users(id) on delete cascade,
  joined_at timestamptz not null default now(),
  primary key (couple_id, user_id),
  unique (user_id)
);

alter table public.couples enable row level security;
alter table public.couple_members enable row level security;
revoke all on public.couples from public, anon, authenticated;
revoke all on public.couple_members from public, anon, authenticated;
revoke all on sequence public.couples_id_seq from public, anon, authenticated;

do $$
declare
  v_couple_id bigint;
begin
  if not exists (select 1 from public.couple_members) then
    insert into public.couples default values returning id into v_couple_id;

    insert into public.couple_members(couple_id, user_id)
    select v_couple_id, u.id
    from public.users u;
  end if;
end $$;

alter table public.wishlist_items
  add column if not exists couple_id bigint references public.couples(id) on delete restrict;

update public.wishlist_items wi
set couple_id = cm.couple_id
from public.couple_members cm
where cm.user_id = wi.owner
  and wi.couple_id is null;

do $$
begin
  if exists (select 1 from public.wishlist_items where couple_id is null) then
    raise exception 'wishlist_couple_backfill_incomplete';
  end if;
end $$;

alter table public.wishlist_items
  alter column couple_id set not null;

create index if not exists wishlist_items_couple_scope_idx
  on public.wishlist_items (couple_id, is_shared, status, id desc)
  where deleted_at is null;

-- Resolve app identity by immutable auth.uid() first. Email remains a temporary
-- fallback for older sessions and rollback-only tests without a real auth row.
create or replace function app_private.current_app_user_id()
returns integer
language sql
stable
security definer
set search_path = public, auth, pg_catalog
as $$
  with by_uid as (
    select u.id
    from public.users u
    where auth.uid() is not null
      and u.auth_user_id = auth.uid()
    limit 1
  ),
  by_email as (
    select u.id
    from public.users u
    where u.email is not null
      and lower(u.email) = lower(coalesce(auth.jwt() ->> 'email', ''))
      and not exists (select 1 from by_uid)
    limit 1
  )
  select id from by_uid
  union all
  select id from by_email
  limit 1;
$$;

revoke all on function app_private.current_app_user_id()
  from public, anon, authenticated;

create or replace function app_private.current_couple_id()
returns bigint
language sql
stable
security definer
set search_path = public, app_private, pg_catalog
as $$
  select cm.couple_id
  from public.couple_members cm
  where cm.user_id = app_private.current_app_user_id()
  limit 1;
$$;

create or replace function app_private.user_in_couple(
  p_user_id integer,
  p_couple_id bigint
)
returns boolean
language sql
stable
security definer
set search_path = public, pg_catalog
as $$
  select exists (
    select 1
    from public.couple_members cm
    where cm.user_id = p_user_id
      and cm.couple_id = p_couple_id
  );
$$;

revoke all on function app_private.current_couple_id()
  from public, anon, authenticated;
revoke all on function app_private.user_in_couple(integer, bigint)
  from public, anon, authenticated;

-- One guard protects every current and future SECURITY DEFINER command that
-- inserts or updates wishlist_items. Service/migration writes with no app actor
-- must provide an explicit valid couple_id and are not treated as user actions.
create or replace function app_private.enforce_wishlist_couple_scope()
returns trigger
language plpgsql
security definer
set search_path = public, app_private, pg_catalog
as $$
declare
  v_actor integer := app_private.current_app_user_id();
  v_couple_id bigint;
begin
  if v_actor is null then
    return new;
  end if;

  v_couple_id := app_private.current_couple_id();
  if v_couple_id is null then
    raise exception 'couple_membership_required' using errcode = '42501';
  end if;

  if tg_op = 'INSERT' then
    new.couple_id := coalesce(new.couple_id, v_couple_id);
  elsif old.couple_id is distinct from v_couple_id then
    raise exception 'wishlist_couple_forbidden' using errcode = '42501';
  end if;

  if new.couple_id is distinct from v_couple_id then
    raise exception 'wishlist_couple_forbidden' using errcode = '42501';
  end if;

  if not app_private.user_in_couple(new.owner, v_couple_id) then
    raise exception 'wishlist_owner_outside_couple' using errcode = '42501';
  end if;

  return new;
end;
$$;

revoke all on function app_private.enforce_wishlist_couple_scope()
  from public, anon, authenticated;

drop trigger if exists wishlist_items_enforce_couple_scope on public.wishlist_items;
create trigger wishlist_items_enforce_couple_scope
before insert or update on public.wishlist_items
for each row execute function app_private.enforce_wishlist_couple_scope();

commit;
