-- Wishlist v3 foundation.
-- IMPORTANT: this repository applies migrations manually through Supabase SQL Editor.
-- Review and run this file before switching the React client to the new RPCs.

begin;

-- 1. Canonical lifecycle -----------------------------------------------------
do $$
begin
  if not exists (select 1 from pg_type where typname = 'wishlist_status') then
    create type public.wishlist_status as enum (
      'created',
      'visible',
      'reserved',
      'preparing_surprise',
      'gifted',
      'archived'
    );
  end if;
end $$;

alter table public.wishlist_items
  add column if not exists status public.wishlist_status,
  add column if not exists archived_at timestamptz,
  add column if not exists deleted_at timestamptz,
  add column if not exists updated_at timestamptz not null default now();

-- Preserve existing production data. fulfilled wins over reserved.
update public.wishlist_items
set status = case
  when coalesce(fulfilled, false) then 'archived'::public.wishlist_status
  when coalesce(reserved, false) then 'reserved'::public.wishlist_status
  else 'visible'::public.wishlist_status
end
where status is null;

update public.wishlist_items
set archived_at = coalesce(archived_at, fulfilled_at, now())
where status = 'archived' and archived_at is null;

alter table public.wishlist_items
  alter column status set default 'visible',
  alter column status set not null;

create index if not exists wishlist_items_owner_status_idx
  on public.wishlist_items (owner, status, id desc)
  where deleted_at is null;

create index if not exists wishlist_items_shared_status_idx
  on public.wishlist_items (is_shared, status, id desc)
  where deleted_at is null;

-- 2. Durable domain records -------------------------------------------------
create table if not exists public.wishlist_reservations (
  id bigint generated by default as identity primary key,
  wish_id bigint not null references public.wishlist_items(id) on delete restrict,
  partner_id integer not null references public.users(id) on delete restrict,
  reserved_at timestamptz not null default now(),
  cancelled_at timestamptz,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint wishlist_reservation_cancel_consistency check (
    (active and cancelled_at is null) or (not active and cancelled_at is not null)
  )
);

create unique index if not exists wishlist_one_active_reservation_idx
  on public.wishlist_reservations (wish_id)
  where active;

create index if not exists wishlist_reservations_partner_idx
  on public.wishlist_reservations (partner_id, active, reserved_at desc);

create table if not exists public.wishlist_gift_completions (
  id bigint generated by default as identity primary key,
  wish_id bigint not null unique references public.wishlist_items(id) on delete restrict,
  completed_by integer not null references public.users(id) on delete restrict,
  completed_at timestamptz not null default now(),
  reaction_photo text,
  reaction_video text,
  comment text,
  idempotency_key uuid not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.wishlist_history (
  id bigint generated by default as identity primary key,
  wish_id bigint not null references public.wishlist_items(id) on delete restrict,
  actor_id integer references public.users(id) on delete set null,
  event_type text not null,
  from_status public.wishlist_status,
  to_status public.wishlist_status,
  metadata jsonb not null default '{}'::jsonb,
  is_private boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists wishlist_history_wish_created_idx
  on public.wishlist_history (wish_id, created_at desc);

-- Backfill a minimal historical baseline for existing wishes.
insert into public.wishlist_history (wish_id, actor_id, event_type, from_status, to_status, is_private, created_at)
select wi.id, wi.owner, 'wish_migrated', null, wi.status, false, now()
from public.wishlist_items wi
where not exists (
  select 1 from public.wishlist_history wh
  where wh.wish_id = wi.id and wh.event_type = 'wish_migrated'
);

-- Backfill active legacy reservations without duplicating reruns.
insert into public.wishlist_reservations (wish_id, partner_id, reserved_at, active)
select wi.id, wi.reserved_by, now(), true
from public.wishlist_items wi
where wi.status in ('reserved', 'preparing_surprise')
  and wi.reserved_by is not null
  and not exists (
    select 1 from public.wishlist_reservations wr
    where wr.wish_id = wi.id and wr.active
  );

-- 3. Authenticated app-user resolution --------------------------------------
create schema if not exists app_private;
revoke all on schema app_private from public, anon, authenticated;

create or replace function app_private.current_app_user_id()
returns integer
language sql
stable
security definer
set search_path = public, auth
as $$
  select u.id
  from public.users u
  where lower(u.email) = lower(coalesce(auth.jwt() ->> 'email', ''))
  limit 1;
$$;

revoke all on function app_private.current_app_user_id() from public, anon, authenticated;

-- 4. Atomic domain RPCs ------------------------------------------------------
create or replace function public.reserve_wishlist_item(p_wish_id bigint)
returns void
language plpgsql
security definer
set search_path = public, app_private
as $$
declare
  v_actor integer := app_private.current_app_user_id();
  v_wish public.wishlist_items%rowtype;
begin
  if v_actor is null then raise exception 'not_authenticated' using errcode = '28000'; end if;

  select * into v_wish
  from public.wishlist_items
  where id = p_wish_id and deleted_at is null
  for update;

  if not found then raise exception 'wish_not_found' using errcode = 'P0002'; end if;
  if v_wish.owner = v_actor and not v_wish.is_shared then
    raise exception 'cannot_reserve_own_wish' using errcode = '42501';
  end if;
  if v_wish.status <> 'visible' then
    raise exception 'wish_not_reservable';
  end if;

  insert into public.wishlist_reservations (wish_id, partner_id)
  values (p_wish_id, v_actor);

  update public.wishlist_items
  set status = 'reserved', reserved = true, reserved_by = v_actor, updated_at = now()
  where id = p_wish_id;

  insert into public.wishlist_history
    (wish_id, actor_id, event_type, from_status, to_status, is_private)
  values
    (p_wish_id, v_actor, 'wish_reserved', 'visible', 'reserved', true);
end;
$$;

create or replace function public.cancel_wishlist_reservation(p_wish_id bigint)
returns void
language plpgsql
security definer
set search_path = public, app_private
as $$
declare
  v_actor integer := app_private.current_app_user_id();
  v_wish public.wishlist_items%rowtype;
begin
  if v_actor is null then raise exception 'not_authenticated' using errcode = '28000'; end if;

  select * into v_wish
  from public.wishlist_items
  where id = p_wish_id and deleted_at is null
  for update;

  if not found then raise exception 'wish_not_found' using errcode = 'P0002'; end if;
  if v_wish.status <> 'reserved' then raise exception 'wish_not_reserved'; end if;

  update public.wishlist_reservations
  set active = false, cancelled_at = now(), updated_at = now()
  where wish_id = p_wish_id and partner_id = v_actor and active;

  if not found then raise exception 'reservation_not_owned' using errcode = '42501'; end if;

  update public.wishlist_items
  set status = 'visible', reserved = false, reserved_by = null, updated_at = now()
  where id = p_wish_id;

  insert into public.wishlist_history
    (wish_id, actor_id, event_type, from_status, to_status, is_private)
  values
    (p_wish_id, v_actor, 'reservation_cancelled', 'reserved', 'visible', true);
end;
$$;

create or replace function public.mark_wishlist_preparing(p_wish_id bigint)
returns void
language plpgsql
security definer
set search_path = public, app_private
as $$
declare
  v_actor integer := app_private.current_app_user_id();
begin
  if v_actor is null then raise exception 'not_authenticated' using errcode = '28000'; end if;

  update public.wishlist_items wi
  set status = 'preparing_surprise', updated_at = now()
  where wi.id = p_wish_id
    and wi.status = 'reserved'
    and exists (
      select 1 from public.wishlist_reservations wr
      where wr.wish_id = wi.id and wr.partner_id = v_actor and wr.active
    );

  if not found then raise exception 'wish_not_preparable' using errcode = '42501'; end if;

  insert into public.wishlist_history
    (wish_id, actor_id, event_type, from_status, to_status, is_private)
  values
    (p_wish_id, v_actor, 'preparing_surprise_started', 'reserved', 'preparing_surprise', true);
end;
$$;

create or replace function public.complete_wishlist_gift(
  p_wish_id bigint,
  p_idempotency_key uuid,
  p_reaction_photo text default null,
  p_reaction_video text default null,
  p_comment text default null
)
returns bigint
language plpgsql
security definer
set search_path = public, app_private
as $$
declare
  v_actor integer := app_private.current_app_user_id();
  v_completion_id bigint;
  v_status public.wishlist_status;
begin
  if v_actor is null then raise exception 'not_authenticated' using errcode = '28000'; end if;

  select id into v_completion_id
  from public.wishlist_gift_completions
  where idempotency_key = p_idempotency_key;

  if found then return v_completion_id; end if;

  select wi.status into v_status
  from public.wishlist_items wi
  where wi.id = p_wish_id and wi.deleted_at is null
  for update;

  if not found then raise exception 'wish_not_found' using errcode = 'P0002'; end if;
  if v_status <> 'preparing_surprise' then raise exception 'wish_not_completable'; end if;
  if not exists (
    select 1 from public.wishlist_reservations wr
    where wr.wish_id = p_wish_id and wr.partner_id = v_actor and wr.active
  ) then
    raise exception 'reservation_not_owned' using errcode = '42501';
  end if;

  insert into public.wishlist_gift_completions (
    wish_id, completed_by, reaction_photo, reaction_video, comment, idempotency_key
  ) values (
    p_wish_id, v_actor, p_reaction_photo, p_reaction_video, p_comment, p_idempotency_key
  ) returning id into v_completion_id;

  update public.wishlist_reservations
  set active = false, cancelled_at = now(), updated_at = now()
  where wish_id = p_wish_id and active;

  update public.wishlist_items
  set status = 'archived',
      fulfilled = true,
      fulfilled_by = v_actor,
      fulfilled_at = now(),
      archived_at = now(),
      reserved = false,
      reserved_by = null,
      updated_at = now()
  where id = p_wish_id;

  insert into public.wishlist_history
    (wish_id, actor_id, event_type, from_status, to_status, is_private)
  values
    (p_wish_id, v_actor, 'gift_completed', 'preparing_surprise', 'gifted', false),
    (p_wish_id, v_actor, 'wish_archived', 'gifted', 'archived', false);

  return v_completion_id;
end;
$$;

revoke all on function public.reserve_wishlist_item(bigint) from public, anon;
revoke all on function public.cancel_wishlist_reservation(bigint) from public, anon;
revoke all on function public.mark_wishlist_preparing(bigint) from public, anon;
revoke all on function public.complete_wishlist_gift(bigint, uuid, text, text, text) from public, anon;

grant execute on function public.reserve_wishlist_item(bigint) to authenticated;
grant execute on function public.cancel_wishlist_reservation(bigint) to authenticated;
grant execute on function public.mark_wishlist_preparing(bigint) to authenticated;
grant execute on function public.complete_wishlist_gift(bigint, uuid, text, text, text) to authenticated;

-- New domain tables are not directly client-readable. Access will be exposed
-- through role-safe RPCs/views in the next migration.
alter table public.wishlist_reservations enable row level security;
alter table public.wishlist_gift_completions enable row level security;
alter table public.wishlist_history enable row level security;

revoke all on public.wishlist_reservations from anon, authenticated;
revoke all on public.wishlist_gift_completions from anon, authenticated;
revoke all on public.wishlist_history from anon, authenticated;

commit;
