-- Wishlist notification inbox.
--
-- Public/private boundary:
--   * only non-private wishlist_history events may emit notifications;
--   * reserved/purchased/preparing events are marked private and ignored;
--   * authenticated users may SELECT only their own inbox rows;
--   * all writes happen through trigger/RPC functions.

begin;

create table if not exists public.app_notifications (
  id bigint generated by default as identity primary key,
  recipient_id integer not null references public.users(id) on delete cascade,
  actor_id integer references public.users(id) on delete set null,
  kind text not null check (kind in (
    'wishlist_new_wish',
    'wishlist_shared_wish',
    'wishlist_gift_completed',
    'wishlist_gift_memory'
  )),
  title text not null check (char_length(title) between 1 and 160),
  body text,
  href text not null check (char_length(href) between 1 and 300),
  entity_id bigint,
  dedupe_key text not null check (char_length(dedupe_key) between 1 and 240),
  read_at timestamptz,
  created_at timestamptz not null default now(),
  unique (recipient_id, dedupe_key)
);

create index if not exists app_notifications_recipient_created_idx
  on public.app_notifications (recipient_id, created_at desc, id desc);

create index if not exists app_notifications_unread_idx
  on public.app_notifications (recipient_id, created_at desc)
  where read_at is null;

alter table public.app_notifications enable row level security;

drop policy if exists app_notifications_recipient_select on public.app_notifications;

-- Safe boolean helper for Realtime/PostgREST RLS. It reveals no user data.
create or replace function public.app_notification_recipient_allowed(p_recipient_id integer)
returns boolean
language sql
stable
security definer
set search_path = public, app_private
as $$
  select p_recipient_id is not distinct from app_private.current_app_user_id();
$$;

revoke all on function public.app_notification_recipient_allowed(integer)
  from public, anon;
grant execute on function public.app_notification_recipient_allowed(integer)
  to authenticated;

create policy app_notifications_recipient_select
on public.app_notifications
for select
to authenticated
using (public.app_notification_recipient_allowed(recipient_id));

revoke all privileges on table public.app_notifications from public, anon, authenticated;
grant select on table public.app_notifications to authenticated;
revoke all privileges on sequence public.app_notifications_id_seq from public, anon, authenticated;

-- Idempotent internal enqueue helper.
create or replace function app_private.enqueue_app_notification(
  p_recipient_id integer,
  p_actor_id integer,
  p_kind text,
  p_title text,
  p_body text,
  p_href text,
  p_entity_id bigint,
  p_dedupe_key text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_recipient_id is null or p_actor_id is null or p_recipient_id = p_actor_id then
    return;
  end if;

  insert into public.app_notifications (
    recipient_id,
    actor_id,
    kind,
    title,
    body,
    href,
    entity_id,
    dedupe_key
  ) values (
    p_recipient_id,
    p_actor_id,
    p_kind,
    left(p_title, 160),
    nullif(left(coalesce(p_body, ''), 1000), ''),
    left(p_href, 300),
    p_entity_id,
    left(p_dedupe_key, 240)
  )
  on conflict (recipient_id, dedupe_key) do nothing;
end;
$$;

revoke all on function app_private.enqueue_app_notification(integer, integer, text, text, text, text, bigint, text)
  from public, anon, authenticated;

-- Convert public Wishlist domain events to recipient-specific inbox rows.
create or replace function app_private.emit_wishlist_notification()
returns trigger
language plpgsql
security definer
set search_path = public, app_private
as $$
declare
  v_title text;
  v_owner integer;
  v_shared boolean;
  v_recipient integer;
  v_href text;
  v_notification_title text;
  v_has_memory boolean;
begin
  -- Private lifecycle events must never reach the wish owner.
  if coalesce(new.is_private, false) or new.actor_id is null then
    return new;
  end if;

  if new.event_type not in (
    'wish_created',
    'wish_moved',
    'gift_completed',
    'gift_memory_created'
  ) then
    return new;
  end if;

  select wi.title, wi.owner, wi.is_shared
    into v_title, v_owner, v_shared
  from public.wishlist_items wi
  where wi.id = new.wish_id
    and wi.deleted_at is null;

  if not found then
    return new;
  end if;

  if new.event_type = 'wish_created' then
    for v_recipient in
      select u.id from public.users u where u.id <> new.actor_id
    loop
      if v_shared then
        v_href := '/wishlist?tab=shared';
        v_notification_title := 'Нове спільне бажання';
      elsif v_owner = v_recipient then
        v_href := '/wishlist?tab=me';
        v_notification_title := 'Партнер додав бажання для тебе';
      else
        v_href := '/wishlist?tab=partner';
        v_notification_title := 'У партнера нове бажання';
      end if;

      perform app_private.enqueue_app_notification(
        v_recipient,
        new.actor_id,
        case when v_shared then 'wishlist_shared_wish' else 'wishlist_new_wish' end,
        v_notification_title,
        v_title,
        v_href,
        new.wish_id,
        format('wishlist:%s:%s', new.event_type, new.id)
      );
    end loop;

  elsif new.event_type = 'wish_moved' then
    if not coalesce((new.metadata ->> 'is_shared')::boolean, false) then
      return new;
    end if;

    for v_recipient in
      select u.id from public.users u where u.id <> new.actor_id
    loop
      perform app_private.enqueue_app_notification(
        v_recipient,
        new.actor_id,
        'wishlist_shared_wish',
        'Бажання стало спільним',
        v_title,
        '/wishlist?tab=shared',
        new.wish_id,
        format('wishlist:%s:%s', new.event_type, new.id)
      );
    end loop;

  elsif new.event_type = 'gift_completed' then
    perform app_private.enqueue_app_notification(
      v_owner,
      new.actor_id,
      'wishlist_gift_completed',
      'Подарунок вручено 🎁',
      v_title,
      '/wishlist?tab=me&archive=1',
      new.wish_id,
      format('wishlist:%s:%s', new.event_type, new.id)
    );

  elsif new.event_type = 'gift_memory_created' then
    v_has_memory :=
      coalesce((new.metadata ->> 'has_photo')::boolean, false)
      or coalesce((new.metadata ->> 'has_video')::boolean, false)
      or coalesce((new.metadata ->> 'has_comment')::boolean, false);

    if v_has_memory then
      perform app_private.enqueue_app_notification(
        v_owner,
        new.actor_id,
        'wishlist_gift_memory',
        'Новий спогад у Gift Archive',
        v_title,
        '/wishlist?tab=me&archive=1',
        new.wish_id,
        format('wishlist:%s:%s', new.event_type, new.id)
      );
    end if;
  end if;

  return new;
end;
$$;

revoke all on function app_private.emit_wishlist_notification()
  from public, anon, authenticated;

drop trigger if exists wishlist_history_emit_notification on public.wishlist_history;
create trigger wishlist_history_emit_notification
after insert on public.wishlist_history
for each row execute function app_private.emit_wishlist_notification();

-- Safe inbox RPCs ------------------------------------------------------------

create or replace function public.get_app_notifications(p_limit integer default 40)
returns table (
  id bigint,
  kind text,
  title text,
  body text,
  href text,
  entity_id bigint,
  actor_id integer,
  actor_name text,
  read_at timestamptz,
  created_at timestamptz
)
language plpgsql
stable
security definer
set search_path = public, app_private
as $$
declare
  v_actor integer := app_private.current_app_user_id();
begin
  if v_actor is null then
    raise exception 'not_authenticated' using errcode = '28000';
  end if;

  return query
  select
    n.id,
    n.kind,
    n.title,
    n.body,
    n.href,
    n.entity_id,
    n.actor_id,
    u.name::text as actor_name,
    n.read_at,
    n.created_at
  from public.app_notifications n
  left join public.users u on u.id = n.actor_id
  where n.recipient_id = v_actor
  order by n.created_at desc, n.id desc
  limit least(greatest(coalesce(p_limit, 40), 1), 100);
end;
$$;

create or replace function public.get_app_notification_unread_count()
returns bigint
language plpgsql
stable
security definer
set search_path = public, app_private
as $$
declare
  v_actor integer := app_private.current_app_user_id();
  v_count bigint;
begin
  if v_actor is null then
    raise exception 'not_authenticated' using errcode = '28000';
  end if;

  select count(*) into v_count
  from public.app_notifications n
  where n.recipient_id = v_actor and n.read_at is null;

  return v_count;
end;
$$;

create or replace function public.mark_app_notification_read(p_notification_id bigint)
returns void
language plpgsql
security definer
set search_path = public, app_private
as $$
declare
  v_actor integer := app_private.current_app_user_id();
begin
  if v_actor is null then
    raise exception 'not_authenticated' using errcode = '28000';
  end if;

  update public.app_notifications
  set read_at = coalesce(read_at, now())
  where id = p_notification_id and recipient_id = v_actor;

  if not found then
    raise exception 'notification_not_found' using errcode = 'P0002';
  end if;
end;
$$;

create or replace function public.mark_all_app_notifications_read()
returns integer
language plpgsql
security definer
set search_path = public, app_private
as $$
declare
  v_actor integer := app_private.current_app_user_id();
  v_count integer;
begin
  if v_actor is null then
    raise exception 'not_authenticated' using errcode = '28000';
  end if;

  update public.app_notifications
  set read_at = now()
  where recipient_id = v_actor and read_at is null;

  get diagnostics v_count = row_count;
  return v_count;
end;
$$;

revoke all on function public.get_app_notifications(integer) from public, anon;
revoke all on function public.get_app_notification_unread_count() from public, anon;
revoke all on function public.mark_app_notification_read(bigint) from public, anon;
revoke all on function public.mark_all_app_notifications_read() from public, anon;

grant execute on function public.get_app_notifications(integer) to authenticated;
grant execute on function public.get_app_notification_unread_count() to authenticated;
grant execute on function public.mark_app_notification_read(bigint) to authenticated;
grant execute on function public.mark_all_app_notifications_read() to authenticated;

-- Realtime invalidates only the recipient's query because SELECT is RLS-scoped.
do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'app_notifications'
  ) then
    alter publication supabase_realtime add table public.app_notifications;
  end if;
end $$;

commit;
